### PR TITLE
prov/gni: fix problem in gnix_getinfo

### LINKED ISSUE #152: Domain open doesn't appear to set cm_nic->control_progress
On commit 1a4ec5d

```
[----] ../prov/gni/test/datagram.c:403: Assertion failed: cm_nic->control_progress == FI_PROGRESS_MANUAL
[====] dg_alloc_man_prog::dgram_wc_post_exchg_manual: (0.00s)
[====] Synthesis: Tested: 120 | Passing: 119 | Failing: 1 | Crashing: 0
```

### PR DESCRIPTION
**Pull request by hppritcha**
The gni getinfo provider was not allowing
the requester to specify the progress model
for control and data.  This commit fixes this
problem.

@ztiffany 

Fixes #152 

Signed-off-by: Howard Pritchard howardp@lanl.gov

### CODE REVIEW

**Comment by hppritcha** [comment]
bot:retest

**Comment by ztiffany** [comment]
I approve.

**Comment by hppritcha** [comment]
something weird's going on with travis.
I'm using this PR as a test for a jenkins setup.

**Comment by hppritcha** [comment]
bot:retest

**Comment by hppritcha** [comment]
bot:retest

**Comment by hppritcha** [comment]
bot:retest

**Comment by hppritcha** [comment]
bot:retest

**Comment by hppritcha** [comment]
bot:retest

**Comment by hppritcha** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins.open-mpi.org/job/edison_libfabric_pr/9/
Test PASSed.

**Pull request merged**
