### PR TITLE
Topic/jenkins test

### PR DESCRIPTION
**Pull request by hppritcha**
more jenkins testing

### CODE REVIEW

**Comment by hppritcha** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins.open-mpi.org/job/edison_libfabric_pr/17/
Test PASSed.

**Comment by hppritcha** [comment]
test this please

**Comment by hppritcha** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins.open-mpi.org/job/edison_libfabric_pr/19/
Test PASSed.

**Comment by hppritcha** [comment]
test this please

**Comment by hppritcha** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins.open-mpi.org/job/edison_libfabric_pr/21/
Test PASSed.

**Comment by sungeunchoi** [comment]
Testing my jenkins set up.

Can one of the admins verify this patch?

**Comment by hppritcha** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins.open-mpi.org/job/edison_libfabric_pr/23/
Test PASSed.

**Comment by sungeunchoi** [comment]
test this please

**Comment by hppritcha** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins.open-mpi.org/job/edison_libfabric_pr/25/
Test PASSed.

**Comment by sungeunchoi** [comment]
test this please

**Comment by hppritcha** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins.open-mpi.org/job/edison_libfabric_pr/27/
Test PASSed.

**Comment by hppritcha** [comment]
test this please

**Comment by sungeunchoi** [comment]
test this please

**Comment by hppritcha** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins.open-mpi.org/job/edison_libfabric_pr/29/
Test PASSed.

**Comment by hppritcha** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins.open-mpi.org/job/edison_libfabric_pr/31/
Test PASSed.

**Comment by sungeunchoi** [comment]
test this please (Howard I realized it doesn't matter if I use a different PR b/c it would still trigger your builds).

**Comment by hppritcha** [comment]
somethings busted now

**Comment by hppritcha** [comment]
closing this to try out a new

**Pull request closed without merging**
