### PR TITLE
prov/gni: add a makefile for gni prov

### PR DESCRIPTION
**Pull request by hppritcha**
There's been a request to be able to have a different
layout of the gni provider source, a subdir for include
files, one for src files, and at some point, one for
sanity unit tests (not to replace fabtests).

Also move the gni part of the top level Makefile.am
into an included Makefile.  This allows us to make the
gni provider specific Makefile.am fancier without
needing to change the shared toplevel Makefile.am

@bturrubiates 
@sungeunchoi 
@ztiffany 

Signed-off-by: Howard Pritchard howardp@lanl.gov

### CODE REVIEW

**Comment by ztiffany** [comment]
I approve.

**Comment by hppritcha** [comment]
I'll let Ben try out adding some unit tests he's been working on before merging.  May need some tweaking.

**Comment by sungeunchoi** [comment]
:+1:

**Comment by bturrubiates** [comment]
:+1: Was successful in adding unit tests, haven't done too much testing though

**Comment by hppritcha** [comment]
looks like I need to rebase

**Pull request merged**
