### PR TITLE
Replaced tests with parameterized tests

### PR DESCRIPTION
**Pull request by jswaro**
Replaced the traditional test fixtures with
parameterized tests. This shortens the file and reduces
complexity at the cost of verbosity in the test output.

Signed-off-by: James Swaro jswaro@cray.com
@sungeunchoi @hppritcha

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jswaro** [comment]
bot:retest

**Comment by jswaro** [comment]
bot:retest

**Comment by sungeunchoi** [comment]
Are you not using the copyright checker?  Copyright should be 2015-2016.

**Comment by jswaro** [comment]
I should probably update that.

**Comment by sungeunchoi** [comment]
:+1:

**Pull request merged**
