### PR TITLE
Cleanup GNI_AV_LOOKUP

### LINKED ISSUE #306: Refactor gnix_av_lookup
As mentioned in #299, use of gnix_av_lookup is a bit contorted if you only care about a subset of the structure (see _gnix_av_addr_retrieve).

### PR DESCRIPTION
**Pull request by jshimek**
Fixes #306

@sungeunchoi @jswaro @ztiffany @hppritcha

### CODE REVIEW

**Comment by jswaro** [comment]
Looks fine. Structure seems to be an oddly named parameter.

**Comment by sungeunchoi** [comment]
I agree with @jswaro.  What about something like `min_size` or `truncated_size` or ...  hmm...  I'm not exactly liking any of those either.

**Comment by hppritcha** [comment]
This is okay although I agree the `structure` name seems a little odd.

**Comment by jshimek** [comment]
The structure variable is meant to imply that you are passing in the size of the structure that you are expecting the function users of the function to copy. Alternatives to structure off the top of my head are min_copy_size, size_struct_copy, and sungeunchoi suggested min_size/ truncated_size

**Comment by sungeunchoi** [comment]
I think I like size_struct_copy or maybe struct_copy_size.

**Comment by sungeunchoi** [comment]
:+1:

**Pull request merged**
