### PR TITLE
Added valgrind suppression file for gnitest executable

### LINKED ISSUE #176: Create valgrind surpression file

### PR DESCRIPTION
**Pull request by jswaro**
Adds a valgrind suppression file for gnitest

run valgrind with --suppression=prov/gni/contrib/gnitest.supp to use the suppression file

Signed-off-by: James Swaro jswaro@cray.com

closes #176

### CODE REVIEW

**Comment by hppritcha** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/edison_libfabric_pr/58/
Test PASSed.

**Comment by jswaro** [comment]
@ztiffany @sungeunchoi @hppritcha 

Review when you can

**Comment by hppritcha** [comment]
looks good !

**Comment by sungeunchoi** [comment]
Is this specific to criterion runs?  If so, maybe name it as such.

**Comment by hppritcha** [comment]
couldn't the fun: specific to criterion be removed and it would still work?

**Comment by hppritcha** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/edison_libfabric_pr/59/
Test PASSed.

**Pull request merged**
