### PR TITLE
Initial implementation of the hashtable to be used in the gnix provider

### LINKED ISSUE #47: Add hash table implementation.
We are in need of a hash table implementation for use in several places. One area in specific that a hash table would be needed is the FI_AV_MAP implementation. Currently I am not storing the stored addresses, and am just fabricating the return value.

### PR DESCRIPTION
**Pull request by jswaro**
The gnix_hashtable_t provides a set of basic functions for interacting with the hashtable as listed below:
-- gnix_ht_init
-- gnix_ht_destroy
-- gnix_ht_insert
-- gnix_ht_remove
-- gnix_ht_lookup
-- gnix_ht_empty

Detailed descriptions of each function are provided in the gnix_hashtable.h
header file.

Included with this commit are the fasthash functions, which will be located
in prov/gni/fasthash with all associated documentation

```
modified:   prov/gni/Makefile.am
new file:   prov/gni/fasthash/README
new file:   prov/gni/fasthash/fasthash.c
new file:   prov/gni/fasthash/fasthash.h
new file:   prov/gni/include/gnix_hashtable.h
new file:   prov/gni/src/gnix_hashtable.c
new file:   prov/gni/test/hashtable.c
```

closes #47

### CODE REVIEW

**Comment by hppritcha** [comment]
probably need to rebase owing to @bturrubiates merging of #124  sorry forgot about the Makefile.am

**Comment by jswaro** [comment]
Done. Waiting on travis CI to say something

**Comment by hppritcha** [comment]
first pass looks good.
@bturrubiates 
@ztiffany 
@sungeunchoi 
could you guys take a look at this too? Sung only if you aren't busy with your talk.

**Comment by ztiffany** [comment]
I thought we agreed to leave locking out of the utilities.

**Comment by jswaro** [comment]
So here is the argument for putting locking into the hash map structure:

If we implement locking internally, we can take a read lock on insert over
the entire hashmap until we know we have to resize. Additionally, the
write lock is only taken on the bucket itself, and only on the entire
hashmap if and only if we need to expand the hashmap. A read lock is only taken over the hashmap and a write lock on the bucket which allows simultaneous removal/insertion/lookup so long as they operate on different buckets. 

Without internal locking, there much be an external lock which must lock
exclusively on insert, regardless of the buckets that aren't being
modified. Otherwise, there is no change. If we think that insertions will
be rare enough to warrant external locking, it won't take much to remove
it. However, from a performance perspective, allowing insertions and
removes to occur at the same time as a lookup so long as they operate on
different buckets is a plus.

-- Jim

**Comment by hppritcha** [comment]
I'm okay with the pthread_rwlock's for now, but I know from experience with thread-hot dmapp that the pthread based rwlock had to be replaced with one that made of use of native atomics.

**Comment by jswaro** [comment]
Is this something we want to remove before it becomes a problem ? If we change the way the internal structures behave later, it will likely cause more problems later than it is worth.

**Comment by ztiffany** [comment]
Your arguments make the assumption that other locks won't be held when operating on a hash table.  This is supposed to be generic.  KISS is my philosophy here.

**Comment by hppritcha** [comment]
Let's discuss this out our telecon this afternoon.

As far as functionality, it matches what I see a need for right now.  The `gnix_ht_insert` returning ENOSPC if an entry with that key already exists is very helpful.

**Pull request merged**
