### PR TITLE
Set cookie during cm_nic allocation.

### LINKED ISSUE #71: cookie not being set in newly created cm_nic
The multi-dom test is failing because the cookie is not being set in the cm_nic struct.

@ztiffany

### PR DESCRIPTION
**Pull request by ztiffany**
Fixes ofi-cray/libfabric-cray#71.

Signed-off-by: Zach Tiffany ztiffany@cray.com

@sungeunchoi @hppritcha

### CODE REVIEW

**Comment by sungeunchoi** [comment]
Did the type of `ptag` change also?  In any case, looks good.

**Comment by bturrubiates** [comment]
@ztiffany Could you also set the cookie in gnix_ep.c (gnix_ep_open) around line 767? I think you might also want to be setting the ptag as well there, but I'm not sure since I know there is faking that goes on somewhere.

@hppritcha Could you chime in on whether or not the ptag should also be set in gnix_ep.c (gnix_ep_open)?

**Comment by ztiffany** [comment]
The ptag is a u8 before it's passed into gnix_cm_nic_alloc().  The parameter list for cm_nic_alloc was just broken.  I'll take a look at ep_open() but it would be nice to merge this today so the jenkins build passes.

**Comment by ztiffany** [comment]
I think gnix_ep_open() needs a few fixes but that's not related to this.  There is code that should limit the number of GNI EPs/domain to 4.  That's not working.

**Comment by hppritcha** [comment]
The ptag/cookie should also set in the gnix_ep_open.  I'm refactoring that code so don't bother with
it.

This looks good.  I'll go ahead and merge it.

**Pull request merged**
