### PR TITLE
Set the gnix fabric version to 1.0

### PR DESCRIPTION
**Pull request by jswaro**
Signed-off-by: James Swaro jswaro@cray.com

### CODE REVIEW

**Comment by jswaro** [comment]
closes #351

**Comment by sungeunchoi** [comment]
Actually, you should be changing GNI_MAJOR_VERSION and GNI_MINOR_VERSION in gnix.h.  There's an assignment to prov_version in the initializer for gnix_fabric_attr.

**Comment by hppritcha** [comment]
@jswaro :+1: for the code change itself.

Note that I'm pretty sure adding a closes issue in a subsequent comment will not close it when the PR is merged.  Rather, one needs to update commit.  Would you mind amending the commit itself?  Or you can just manually close the issue.

**Comment by sungeunchoi** [comment]
:+1:

**Pull request merged**
