### PR TITLE
prov/gni Remove tag by request should use &element->free

### LINKED ISSUE #634: gnix_tag_list_remove_tag_by_req uses base address instead of absolute address when assigning the dlist_entry pointer
>   element = &req->msg.tle;
>   item = (struct dlist_entry *) element;

This should be the following, or something similar:

>   element = &req->msg.tle;
>   item = (struct dlist_entry *) &element->free;

### PR DESCRIPTION
**Pull request by chuckfossen**
Change item assignment to use &element->free instead of element.

Fixes #634

Signed-off-by: Chuck Fossen chuckf@cray.com

@jswaro @sungeunchoi

### CODE REVIEW

**Comment by sungeunchoi** [comment]
Is there a unit test for this?  If not, should there be?

**Comment by chuckfossen** [comment]
I believe so. Let me check.

**Comment by sungeunchoi** [comment]
:+1:

**Comment by hppritcha** [comment]
looks good!

**Pull request merged**
