### PR TITLE
Fix VA calculation in _gnix_convert_key_to_mhdl.

### LINKED ISSUE #204: _gnix_convert_key_to_mhdl truncates mem handle VA
From _gnix_convert_key_to_mhdl:
       uint64_t va = (uint64_t) __sign_extend(key->pfn << GNIX_MR_PAGE_SHIFT,
                       GNIX_MR_VA_BITS);

VA is truncated when this shift is done from the pfn bitfield.
  key->pfn << NIX_MR_PAGE_SHIFT

### PR DESCRIPTION
**Pull request by ztiffany**
Fixes ofi-cray/libfabric-cray#204.

Signed-off-by: Zach Tiffany ztiffany@cray.com

### CODE REVIEW

**Comment by ztiffany** [comment]
@hppritcha @sungeunchoi @jswaro

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/edison_libfabric_pr/97/

**Build Log**
_last 20 lines_

```
[...truncated 204 lines...]
prov/gni/src/gnix_eq.c: At top level:
prov/gni/src/gnix_eq.c:158:16: warning: 'gnix_eq_write_error' defined but not used [-Wunused-function]
 static ssize_t gnix_eq_write_error(struct fid_eq *eq, fid_t fid,
                ^
  CC       prov/gni/src/src_libfabric_la-gnix_mr.lo
  CC       prov/gni/src/src_libfabric_la-gnix_cm.lo
prov/gni/src/gnix_mr.c: In function '_gnix_convert_key_to_mhdl':
prov/gni/src/gnix_mr.c:241:38: error: 'PAGE_SHIFT' undeclared (first use in this function)
  va = (uint64_t) __sign_extend(va << PAGE_SHIFT, GNIX_MR_VA_BITS);
                                      ^
prov/gni/src/gnix_mr.c:241:38: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [prov/gni/src/src_libfabric_la-gnix_mr.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/edison_libfabric_pr'
make: *** [all] Error 2
Build step 'Execute shell' marked build as failure
An attempt to send an e-mail to empty list of recipients, ignored.
GCM: Sending notification to: hpp
Setting status of f6089fb3a5492b56cfbd0392fb577afaa7b4ad1e to FAILURE with url http://jenkins.open-mpi.org/job/edison_libfabric_pr/97/ and message: Build finished.
```

Test FAILed.

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/edison_libfabric_pr/98/
Test PASSed.

**Comment by sungeunchoi** [comment]
:-1:

**Comment by sungeunchoi** [comment]
:+1:

**Comment by hppritcha** [comment]
why is gnitest part of the commit?  I don't think that should be going in to github repo.

**Pull request merged**
