### PR TITLE
Add hint to specify use of GNI fabric in CQ unit test.

### LINKED ISSUE #82: gnitest fails on Tiger
When using Snaipe/Criterion@260b88c, GCC 4.8.1, and GNU Gettext 0.17 @hppritcha gets the following error output.

Testing with the same environment on Edison is successful. 

First guess is setting up the CQ stuff beforehand is failing.

```
n17276@tiger:~/libfabric_install/bin>srun -n 1 -N 1 ./gnitest
[----] prov/gni/test/cq.c:366: Assertion failed: !cq_priv->ev_queue.head
[====] cq_msg::fill: (0.00s)
[----] prov/gni/test/cq.c:425: Assertion failed: !cq_priv->ev_queue.head
[====] cq_msg::multi_read: (0.00s)
[----] prov/gni/test/cq.c:334: Assertion failed: !cq_priv->ev_queue.head
[====] cq_msg::single: (0.00s)
[----] prov/gni/test/cq.c:167: Assertion failed: cq_priv->entry_size == sizeof(struct fi_cq_entry)
[====] creation::format_context: (0.00s)
[----] prov/gni/test/cq.c:193: Assertion failed: cq_priv->entry_size == sizeof(struct fi_cq_data_entry)
[====] creation::format_data: (0.00s)
[----] prov/gni/test/cq.c:180: Assertion failed: cq_priv->entry_size == sizeof(struct fi_cq_msg_entry)
[====] creation::format_msg: (0.00s)
[----] prov/gni/test/cq.c:206: Assertion failed: cq_priv->entry_size == sizeof(struct fi_cq_tagged_entry)
[====] creation::format_tagged: (0.00s)
[----] prov/gni/test/cq.c:151: Assertion failed: fi_cq_open
[====] creation::format_unspec: (0.00s)
[----] prov/gni/test/cq.c:151: Unexpected signal caught below this line!
[====] creation::format_unspec: CRASH!
[----] prov/gni/test/cq.c:100: Assertion failed: fi_cq_open
[----] prov/gni/test/cq.c:100: Unexpected signal caught below this line!
[====] insertion::limit: CRASH!
[----] prov/gni/test/cq.c:100: Assertion failed: fi_cq_open
[----] prov/gni/test/cq.c:100: Unexpected signal caught below this line!
[====] insertion::single: CRASH!
[----] prov/gni/test/cq.c:100: Assertion failed: fi_cq_open
[----] prov/gni/test/cq.c:100: Unexpected signal caught below this line!
[====] reading::empty: CRASH!
[----] prov/gni/test/cq.c:100: Assertion failed: fi_cq_open
[----] prov/gni/test/cq.c:100: Unexpected signal caught below this line!
[====] reading::error: CRASH!
[====] Synthesis: Tested: 12 | Passing: 0 | Failing: 13 | Crashing: 5 
srun: error: nid00010: task 0: Exited with exit code 1
```

### PR DESCRIPTION
**Pull request by bturrubiates**
Fixes #82

Signed-off-by: Ben Turrubiates bturrubiates@lanl.gov

### CODE REVIEW

**Comment by bturrubiates** [comment]
@hppritcha Can you verify that this fixes the test failures for you?

**Comment by bturrubiates** [comment]
@sungeunchoi Forgot to tag

**Comment by sungeunchoi** [comment]
:+1:

**Comment by hppritcha** [comment]
works for me.  merging.

**Pull request merged**
