### PR TITLE
Topic/generic queue

### LINKED ISSUE #115: Implement generic queue structure that can be used for both CQ and EQ.

### PR DESCRIPTION
**Pull request by bturrubiates**
Closes #115 

This is another attempt at cleaning up the queue code. Trying to decouple the CQ and EQ from the actual queue implementation. 

@hppritcha @sungeunchoi @jswaro @ztiffany Thoughts?

### CODE REVIEW

**Comment by bturrubiates** [comment]
Actually, need to reevaluate this a bit. After working on #116 it seems I can still generalize further.

**Comment by jswaro** [comment]
Not to be picky, but the pull request is a bit messy. Some of the code has nothing to do with the queue work. Perhaps this should be split up into different topics/pulls?

**Comment by hppritcha** [comment]
The changes look good but it would help if the PR could be broken up into 2.  First one with the addition of the  new gnix_queue functionality, but no changes to the existing cq/eq code, then a second PR with the changes to the cq/eq code to switch over to use the new gnix_queue.  But if this is too much trouble then keep it like it is.

**Comment by bturrubiates** [comment]
Sure I can do that.

## 

Benjamin Turrubiates
Phone: (956) 802-9037

On Mon, Apr 27, 2015 at 10:35 AM, Howard Pritchard <notifications@github.com

**Pull request closed without merging**
