### PR TITLE
Implement FI_SOURCE capability.

### PR DESCRIPTION
**Pull request by ztiffany**
Fixes ofi-cray/libfabric-cray#348.

Signed-off-by: Zach Tiffany ztiffany@cray.com

### CODE REVIEW

**Comment by ztiffany** [comment]
@hppritcha @sungeunchoi @jswaro

**Comment by sungeunchoi** [comment]
:+1:

**Comment by hppritcha** [comment]
Looks good, although it appears the an app using FI_SOURCE should expect slower message rates.
I don't think mpi's will ever use FI_SOURCE, but maybe shmem/chapel etc?  Might be good to double check with them if they are thinking about using this and if so, for what.  If it would just be for control messages, I think the O(N) where N == number of VC's lookup method is okay if this is the case.

**Comment by ztiffany** [comment]
Reverse lookup of a VC's fi_addr should only be done during the first recv.  If FI_SOURCE is not used by the EP, a lookup is never attempted.

**Comment by hppritcha** [comment]
oh I see.  Didn't catch that.

**Pull request merged**
