### PR TITLE
prov/gni: Disable cm test

### PR DESCRIPTION
**Pull request by sungeunchoi**
Also change output to debug output and add curly braces around
conditionals with only debug printfs.

@hppritcha @chuckfossen 

Signed-off-by: Sung-Eun Choi <sungeunchoi@users.noreply.github.com>

### CODE REVIEW

**Comment by hppritcha** [comment]
:+1:

**Comment by chuckfossen** [comment]
👍

**Comment by sungeunchoi** [comment]
@ztiffany This test failed the jenkins tests.  Maybe it has to do with the fact that we build all the valid providers.

**Comment by hppritcha** [comment]
why would building other providers cause the test to fail?

**Comment by sungeunchoi** [comment]
I'm just naming one of the major things that's different in the jenkins build.

**Comment by sungeunchoi** [comment]
Sorry, I just looked at the actual log rather than the script and here's the full configure line:

```
./configure --disable-verbs --disable-usnic --disable-rxm --disable-rxd --with-kdreg=/path/to/kdeg-devel --prefix=/path/to/prefix --with-criterion=/path/to/criterion
```

At some point we were having trouble with the verbs and usnic builds, so I disabled those.  The rxd and rxm providers IMO are still trying to figure out what they're supposed to be, so I disabled those.

**Pull request merged**
