### PR TITLE
prov/gni: Add vc lookup perf test.

### PR DESCRIPTION
**Pull request by ztiffany**
Signed-off-by: Zach Tiffany ztiffany@cray.com

@hppritcha

### CODE REVIEW

**Comment by ztiffany** [comment]
Test is disabled by default.  Current output looks like:

```
tiger$ ./prov/gni/test/run_gnitest   --pattern=vc_lookup/perf 2>&1 |tee test.out
type: MAP   npeers:       2 naddrs:       2 ns: 108.880000
type: MAP   npeers:      64 naddrs:       2 ns: 105.210000
type: MAP   npeers:      64 naddrs:      64 ns: 105.270000
type: MAP   npeers:    2048 naddrs:       2 ns: 104.950000
type: MAP   npeers:    2048 naddrs:      64 ns: 104.860000
type: MAP   npeers:    2048 naddrs:    2048 ns: 111.130000
type: MAP   npeers:   65536 naddrs:       2 ns: 105.310000
type: MAP   npeers:   65536 naddrs:      64 ns: 117.740000
type: MAP   npeers:   65536 naddrs:    2048 ns: 105.850000
type: MAP   npeers:   65536 naddrs:   65536 ns: 108.630000
type: MAP   npeers: 2097152 naddrs:       2 ns: 103.790000
type: MAP   npeers: 2097152 naddrs:      64 ns: 113.770000
type: MAP   npeers: 2097152 naddrs:    2048 ns: 117.400000
type: MAP   npeers: 2097152 naddrs:   65536 ns: 107.150000
type: MAP   npeers: 2097152 naddrs: 2097152 ns: 101.460000
type: TABLE npeers:       2 naddrs:       2 ns: 35.240000
type: TABLE npeers:      64 naddrs:       2 ns: 34.950000
type: TABLE npeers:      64 naddrs:      64 ns: 48.250000
type: TABLE npeers:    2048 naddrs:       2 ns: 35.360000
type: TABLE npeers:    2048 naddrs:      64 ns: 48.630000
type: TABLE npeers:    2048 naddrs:    2048 ns: 49.390000
type: TABLE npeers:   65536 naddrs:       2 ns: 35.420000
type: TABLE npeers:   65536 naddrs:      64 ns: 66.730000
type: TABLE npeers:   65536 naddrs:    2048 ns: 51.990000
type: TABLE npeers:   65536 naddrs:   65536 ns: 47.370000
type: TABLE npeers: 2097152 naddrs:       2 ns: 34.150000
type: TABLE npeers: 2097152 naddrs:      64 ns: 79.890000
type: TABLE npeers: 2097152 naddrs:    2048 ns: 135.130000
type: TABLE npeers: 2097152 naddrs:   65536 ns: 76.990000
type: TABLE npeers: 2097152 naddrs: 2097152 ns: 47.270000
```

**Comment by hppritcha** [comment]
:+1:

**Comment by chuckfossen** [comment]
Do you get those same numbers consistently? The TABLE numbers look odd to me - especially the line:
type: TABLE npeers: 2097152 naddrs:    2048 ns: 135.130000

**Comment by ztiffany** [comment]
@chuckfossen Yes, results are pretty consistent.  There must be something strange that happens in that case.

**Comment by ztiffany** [comment]
I have some fixes that make the performance make more sense.  I'll commit them right after this.

**Comment by hppritcha** [comment]
looks good.  given the borked up state of github today, I'm going to merge this myself once the "checking for ability to merge automatically" check is finally done.

**Pull request merged**
