### PR TITLE
prov/gni: Fixed iov bugs.

### PR DESCRIPTION
**Pull request by e-harvey**
- For a partial read, the iov send_len was never
    updated after moving the pointer.
- When the size of a chained transaction exceeded
    the max chained transaction size, the txd was
    stomped on before storing it into the list.

@sungeunchoi @ztiffany @hppritcha

### CODE REVIEW

**Comment by hppritcha** [comment]
looks good, but was there a test which showed this bug?

**Comment by e-harvey** [comment]
No, I noticed it when looking into implementing #886.

On Sat, Jul 16, 2016 at 11:45 AM -0500, "Howard Pritchard" <notifications@github.com<mailto:notifications@github.com>> wrote:

looks good, but was there a test which showed this bug?

##

**Comment by sungeunchoi** [comment]
Would it be easy to add such a test case?

**Comment by e-harvey** [comment]
> Would it be easy to add such a test case?
> Yes.

The change on line 667 and 1124 will be exercised by the existing tests in prov/gni/test/rdm_sr.c and prov/gni/test/rdm_tagged_sr.c.

However, the change on line 1025 will require adjusting the rendezvous threshold in the domain parameters.

**Comment by e-harvey** [comment]
It turns out that the rendezvous threshold cannot be increased to trigger the conditional on line 1025 due to hard limits (GNI_SMSG_MAX_SIZE) defined within uGNI.  I will update this PR with the appropriate changes.

**Comment by ztiffany** [comment]
:+1:

**Comment by hppritcha** [comment]
Looks good.  I think this is ready to go.

**Pull request merged**
