### PR TITLE
prov/gni: Add return value checks to calls to fi_close()

### PR DESCRIPTION
**Pull request by sungeunchoi**
Signed-off-by: Sung-Eun Choi <sungeunchoi@users.noreply.github.com>

### CODE REVIEW

**Comment by hppritcha** [comment]
Does this fix an outstanding problem?  I've no issue with the changes, just wondering why the addition.

**Comment by sungeunchoi** [comment]
I was in there looking at a valgrind leak (which turned out not to be related), but in trying to figure out what was going on, I had added the ret val checks so I'm checking them in.

**Comment by hppritcha** [comment]
@ztiffany please review when you get a chance.

**Comment by hppritcha** [comment]
:+1:
I'm merging this one.

**Pull request merged**
