### PR TITLE
prov/gni: disallow FI_REMOTE_CQ_DATA w/ readmsg

### PR DESCRIPTION
**Pull request by a-abraham**
As per the spec, the flag only applies to fi_sendmsg and
fi_senddata. The tests created to test FI_REMOTE_CQ_DATA
with readmsg and readdata are also unnecessary.

Fixes ofi-cray/libfabric-cray#1131
Signed-off-by: Amith Abraham <aabraham@cray.com>

@ztiffany @sungeunchoi

### CODE REVIEW

**Comment by a-abraham** [comment]
No hanging in gni_test this time. Those two tests were the issue last week.

**Comment by ztiffany** [comment]
👍

**Comment by a-abraham** [comment]
Added "prov/gni" to commit header  and PR title

**Comment by a-abraham** [comment]
bot:lanl:retest

**Comment by sungeunchoi** [comment]
👍

**Pull request merged**
