### PR TITLE
Add new multithreaded counter tests (and refactor set up to support multiple endpoints)

### PR DESCRIPTION
**Pull request by sungeunchoi**
@hppritcha @ztiffany @jswaro 

Signed-off-by: Sung-Eun Choi sungeunchoi@users.noreply.github.com

### CODE REVIEW

**Comment by hppritcha** [comment]
this is great stuff, but I think the run_gnitest script should be modified to disable slurm/alps binding to a single core by default when using `srun -n 1` or `aprun -n 1`.  I modified the run_gnitest to not use cpu binding and the tests work.   I think it would be good to modify the run_gnitest to include `--cpu_bind=none` for slurm env and `-cc none` for alps env.

**Comment by sungeunchoi** [comment]
That sound good -- okay if I do that in the next commit?

**Comment by sungeunchoi** [comment]
PR #565 does disables CPU bind.

**Comment by hppritcha** [comment]
sounds good - pr 565 I mean

**Pull request merged**
