### PR TITLE
prov/gni: fix potential deadlock in vc wq

### PR DESCRIPTION
**Pull request by hppritcha**
When using multiple threads in the gni provider
are using the same gnix_nic, there was the potential
for hitting the dining philosopher problem when
processing the work queue in one thread and processing
smsg messages in another thread.

This commit fixes that problem.

@ztiffany 
@sungeunchoi you may want to add this in to your patches for Bob's problem

Signed-off-by: Howard Pritchard howardp@lanl.gov

### CODE REVIEW

**Comment by ztiffany** [comment]
Can you describe the problem more?  Is there a reason we can't hold work queue lock continuously?

I think the solution needs to be reworked.  Adding a goto makes the while loop useless.

**Comment by ztiffany** [comment]
I think I see the lock inversion given 2 threads doing CQ progress.

Thread A is doing RX progress on VC X
  -NIC lock is held during SMSG mailbox processing
  -A rendezvous start message is received.
  -That triggers a request to be queued on the work list
  -Thread A attempts to acquire the work list lock
Thread B is doing work progress on VC X
  -Work list lock is held while processing work list
  -A rendezvous request is dequeued
  -Thread B attempts to acquire NIC lock
     -Waits for A

**Comment by hppritcha** [comment]
Exactly, that's what I'm seeing - thanks to lgdb -  once I try to enable a progress thread

**Comment by hppritcha** [comment]
@ztiffany cleaned up the code changes

**Comment by ztiffany** [comment]
:+1:

**Comment by hppritcha** [comment]
@ztiffany I was being an idiot for tx_queue.  the order of the elements in the tx_queue have to remain in the order they were posted by the application,  so I don't plan to push anything for changes in `__gnix_vc_push_tx_reqs`

**Pull request merged**
