### PR TITLE
another test of jenkins

### PR DESCRIPTION
**Pull request by hppritcha**
another test

Signed-off-by: Howard Pritchard howardp@lanl.gov

### CODE REVIEW

**Comment by hppritcha** [comment]
retest this please

**Comment by hppritcha** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins.open-mpi.org/job/edison_libfabric_pr/33/
Test PASSed.

**Comment by hppritcha** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins.open-mpi.org/job/edison_libfabric_pr/36/
Test PASSed.

**Comment by hppritcha** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins.open-mpi.org/job/edison_libfabric_pr/37/
Test FAILed.

**Comment by sungeunchoi** [comment]
retest this please

**Comment by hppritcha** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins.open-mpi.org/job/edison_libfabric_pr/39/
Test FAILed.

**Comment by hppritcha** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins.open-mpi.org/job/edison_libfabric_pr/41/
Test FAILed.

**Comment by hppritcha** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins.open-mpi.org/job/edison_libfabric_pr/42/

**Build Log**
_last 20 lines_

```
[...truncated 200 lines...]
prov/gni/src/gnix_ep.c:622:26: warning: unused variable 'gnix_ep_rma_ops' [-Wunused-variable]
 static struct fi_ops_rma gnix_ep_rma_ops = {
                          ^
prov/gni/src/gnix_ep.c:609:26: warning: unused variable 'gnix_ep_msg_ops' [-Wunused-variable]
 static struct fi_ops_msg gnix_ep_msg_ops = {
                          ^
prov/gni/src/gnix_ep.c:598:25: warning: unused variable 'gnix_ep_ops' [-Wunused-variable]
 static struct fi_ops_ep gnix_ep_ops = {
                         ^
prov/gni/src/gnix_ep.c:591:22: warning: unused variable 'gnix_ep_fi_ops' [-Wunused-variable]
 static struct fi_ops gnix_ep_fi_ops = {
                      ^
make[1]: *** [prov/gni/src/src_libfabric_la-gnix_ep.lo] Error 1
make[1]: Leaving directory `/global/u2/h/hpp/jenkins_edison/workspace/edison_libfabric_pr'
make: *** [all] Error 2
Build step 'Execute shell' marked build as failure
An attempt to send an e-mail to empty list of recipients, ignored.
GCM: Sending notification to: hpp
Setting status of 0f60e11f77a5abb6aa74a2af6bbf39fec9e30ad6 to FAILURE with url http://jenkins.open-mpi.org/job/edison_libfabric_pr/42/ and message: Merged build finished.
```

Test FAILed.

**Comment by hppritcha** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins.open-mpi.org/job/edison_libfabric_pr/43/
Test PASSed.

**Pull request closed without merging**
