### PR TITLE
prov/gni: busy sread() implementation

### PR DESCRIPTION
**Pull request by ztiffany**
This is an inefficient implementation of blocking CQ read functions.

Signed-off-by: Zach Tiffany ztiffany@cray.com

@sungeunchoi @hppritcha @jswaro @chuckfossen

### CODE REVIEW

**Comment by sungeunchoi** [comment]
:+1:

**Comment by ztiffany** [comment]
@chuckfossen Thanks, I missed that.

**Comment by chuckfossen** [comment]
:+1:

**Comment by hppritcha** [comment]
good enough!

**Pull request merged**
