### PR TITLE
Add prov/gni/test/gnitest to .gitignore.

### PR DESCRIPTION
**Pull request by ztiffany**
Signed-off-by: Zach Tiffany ztiffany@cray.com

### CODE REVIEW

**Comment by ztiffany** [comment]
@sungeunchoi

**Comment by lanl-ompi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.open-mpi.org/job/edison_libfabric_pr/102/
Test PASSed.

**Comment by hppritcha** [comment]
looks good

**Comment by sungeunchoi** [comment]
:+1:

**Pull request merged**
