### PR TITLE
Destroy VC in cancel_ep_send test.

### PR DESCRIPTION
**Pull request by sungeunchoi**
@jswaro @ztiffany @hppritcha 

Signed-off-by: Sung-Eun Choi sungeunchoi@users.noreply.github.com

### CODE REVIEW

**Comment by sungeunchoi** [comment]
I think the travis test failure is a false negative.  Nothing in this commit should have affected the sockets commit.

**Comment by ztiffany** [comment]
I'm confused why we're adding _gnix_vc_destroy() in one test and removing it in another.

**Comment by sungeunchoi** [comment]
Good catch.  I need to close this.  I did it before I fixed the vc destroy issue.

**Comment by sungeunchoi** [comment]
I forgot, this test actually allocates the vc manually and doesn't add it to the EP, so it does need to destroy it.

**Comment by hppritcha** [comment]
looks good to me.

**Pull request merged**
