### PR TITLE
Abort on errors

### LINKED ISSUE #438: Change GNIX_ERR to print message and abort

### PR DESCRIPTION
**Pull request by jswaro**
closes #438

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hppritcha** [comment]
bot:retest

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hppritcha** [comment]
hmmm... there is a problem here.  The FI_PRINT is not being defined if NDEBUG.

Howard suggests merging https://github.com/jswaro/libfabric/pull/8 in to this PR to get it
to past the LANL/jenkins test.

@sungeunchoi

**Comment by sungeunchoi** [comment]
:+1:

**Pull request merged**
