### PR TITLE
prov/gni: Break mr_cache into read only and read/write caches

### LINKED ISSUE #1197: FI_REMOTE_WRITE needed even when only using as source buffer
The FI_REMOTE_WRITE flag is needed when registering memory for the source side buffer of an fi_write operation.  According to the man page, this should not be necessary.

Should check if this is also the case for FI_REMOTE_READ.

### PR DESCRIPTION
**Pull request by chuckfossen**
The mr_cache was coalescing read only and read/write memory regions.
Separate them into two caches to avoid this condition.
Update the mr test to handle two caches. Most of the testing is on
the RW cache as that is the default access mode.

fixes ofi-cray/libfabric-cray#1197

Signed-off-by: Chuck Fossen <chuckf@cray.com>
@jswaro @sungeunchoi

### CODE REVIEW

**Comment by hppritcha** [comment]
@chuckfossen could you edit your commit message and remove the '/' betweey cray and #1197?

thanks.

**Comment by chuckfossen** [comment]
ok, done

**Review by jswaro — APPROVED** [review]
Looks fine.

**Comment by sungeunchoi** [comment]
Would make sense to have a lock for each of the cache types?  Other than initialization and teardown, it seems like operations on the caches could occur simultaneously.

**Comment by jswaro** [comment]
I would say that would be opportune. Let's do that.

**Comment by chuckfossen** [comment]
I think that would add complexity without much gain. It may be useful in the autro-registration path but I doubt if users would be doing parallel registrations much. I think separating out the locking would be better in a separate PR.

**Comment by jswaro** [comment]
I think @chuckfossen is right. I don't think it is worth doing from the perspective of this PR, but I can see obvious gains from doing it. Let's table it for now, put it in a RFE task for later and it can be low hanging fruit for another day.

**Comment by sungeunchoi** [comment]
That makes sense.  Let's open an issue about looking into it and leave this PR as is.

**Review by sungeunchoi — APPROVED** [review]

**Comment by hppritcha** [comment]
bot:lanl:retest

**Pull request merged**
