### PR TITLE
prov/gni: debug rdm_atomic/band intermittent failure

### PR DESCRIPTION
**Pull request by chuckfossen**
This is in reference to #1145
Signed-off-by: Chuck Fossen <chuckf@cray.com>

@sungeunchoi @hppritcha

### CODE REVIEW

**Comment by chuckfossen** [comment]
bot:lanl:retest

**Comment by chuckfossen** [comment]
bot:lanl:retest

**Comment by sungeunchoi** [comment]
I'm concerned that this test is one of many that could fail for the same reason.  Could you add the CQ error output for all the tests?

**Comment by chuckfossen** [comment]
I thought about that too but since we haven't seen any others, I thought I'd start with this one.
I can add it to the others as well.

**Comment by hppritcha** [comment]
looks good, but adding it to other tests would be a good idea.

**Comment by chuckfossen** [comment]
I added the debug output for all the tests in rdm_atomic.c

**Comment by sungeunchoi** [comment]
👍

**Pull request merged**
