### PR TITLE
Remove foobar file

### PR DESCRIPTION
**Pull request by bturrubiates**
This file doesn't really belong.

Signed-off-by: Ben Turrubiates bturrubiates@lanl.gov

### CODE REVIEW

**Comment by sungeunchoi** [comment]
Should the commit message make sense to me?

<blockquote>
Add configury to enable spinlock.
</blockquote>

**Comment by bturrubiates** [comment]
Uhh, no that was a mistake...one sec

**Comment by sungeunchoi** [comment]
:+1:

**Comment by hppritcha** [comment]
looks great to me.  foobarrr

**Pull request merged**
