### PR TITLE
prov/gni: minor error reporting fixes for alps

### PR DESCRIPTION
**Pull request by hppritcha**
alps has a strange error reporting scheme which varies
from call type to type.  In this case, use errno
to get the underlying error from alps.

@bturrubiates 
Signed-off-by: Howard Pritchard hppritcha@gmail.com

### CODE REVIEW

**Comment by bturrubiates** [comment]
Oh, thanks. My bad. I just followed the already existing convention when fixing that. I wasn't aware errno would be used. I don't understand that function it 1) returns something, 2) has an in/out error status, 3) sets errno. That seems excessive and unintuitive.

**Comment by hppritcha** [comment]
Ben I decided that the code should report both the error returned by alps lli call (either the return value or the "alp_status") plus any errno.  If errno is zero, strerror just returns "success" or something like that.

**Comment by bturrubiates** [comment]
That sounds good, but would it be better to make the error string say "status=%d" since what you're actually printing is alps_status?

**Comment by hppritcha** [comment]
messed this request up by accident

**Comment by bturrubiates** [comment]
@hppritcha What do you mean?

**Pull request closed without merging**
