### PR TITLE
Fix conflict of assert definition by including criterion last and undefi...

### PR DESCRIPTION
**Pull request by bturrubiates**
...ning assert beforehand.

Signed-off-by: Ben Turrubiates bturrubiates@lanl.gov

### CODE REVIEW

**Comment by bturrubiates** [comment]
@hppritcha @sungeunchoi 
This is already in my topic/cq-wait branch, but it wouldn't hurt to get it in earlier. It might take a while for my cq stuff to get merged....

**Comment by bturrubiates** [comment]
`#undef` should ignore names that are not defined macros, but just to be safe I surrounded with guards.

**Comment by sungeunchoi** [comment]
:+1:

**Comment by jswaro** [comment]
I'm assuming there is a programming environment we are using. What is it?
By default, I'm not seeing C11 support but Sung had mentioned that she had
to change the version of GCC via a system module.

Does this sound familiar to anyone?
-- Jim

**Comment by sungeunchoi** [comment]
For the automatic builds, I'm swapping out the default gcc with 4.9.2.

**Pull request merged**
