### PR TITLE
Remove .travis.yml file

### PR DESCRIPTION
**Pull request by sungeunchoi**
@hppritcha 
Signed-off-by: Sung-Eun Choi sungeunchoi@users.noreply.github.com

### CODE REVIEW

**Comment by hppritcha** [comment]
this is odd.
@sungeunchoi let me know if you don't have time to work on this today.

**Comment by sungeunchoi** [comment]
@hppritcha What's odd?

**Comment by hppritcha** [comment]
that github says it can't merge automatically

**Comment by sungeunchoi** [comment]
@hppritcha It's fixed now.

**Pull request merged**
