### PR TITLE
Save pointer to mbox slab's lock before freeing the mbox itself.

### LINKED ISSUE #421: valgrind: Invalid read in _gnix_mbox_free
Lots of tests see this error:

==547== Invalid read of size 8
==547==    at 0x44D529: _gnix_mbox_free (gnix_mbox_allocator.c:743)
==547==    by 0x455005: _gnix_vc_destroy (gnix_vc.c:954)
==547==    by 0x45B9AF: gnix_ep_close (gnix_ep.c:792)
==547==    by 0x41F065: fi_close (fabric.h:395)
...
==547==  Address 0x649fe38 is 8 bytes inside a block of size 32 free'd
==547==    at 0x4C2923A: free (vg_replace_malloc.c:530)
==547==    by 0x44D528: _gnix_mbox_free (gnix_mbox_allocator.c:742)
==547==    by 0x455005: _gnix_vc_destroy (gnix_vc.c:954)
==547==    by 0x45B9AF: gnix_ep_close (gnix_ep.c:792)
==547==    by 0x41F065: fi_close (fabric.h:395)
...
==547==  Block was alloc'd at
==547==    at 0x4C29E97: calloc (vg_replace_malloc.c:711)
==547==    by 0x44B512: __fill_mbox (gnix_mbox_allocator.c:528)
==547==    by 0x44D0A6: _gnix_mbox_alloc (gnix_mbox_allocator.c:710)
==547==    by 0x4559D8: _gnix_vc_accept (gnix_vc.c:1091)
==547==    by 0x45C9E8: gnix_ep_control (gnix_ep.c:648)
==547==    by 0x420001: fi_enable (fi_endpoint.h:182)
...

### PR DESCRIPTION
**Pull request by sungeunchoi**
Fixes #421 

Let's blame @bturrubiates ;-)

@hppritcha @ztiffany 

Signed-off-by: Sung-Eun Choi sungeunchoi@users.noreply.github.com

### CODE REVIEW

**Comment by bturrubiates** [comment]
Ooooh, ya got me. It's so obvious now! :+1:

**Comment by sungeunchoi** [comment]
@bturrubiates That's okay... you were still young and inexperienced back then (6 months ago)...

**Comment by bturrubiates** [comment]
It's a good thing I have all this experience now after a mere six months. Now I'm immune to mishaps like this.

(I say as I prepare for a future of making this very same mistake...)

:+1: :+1:

**Comment by hppritcha** [comment]
looks good, nice catch.

**Comment by sungeunchoi** [comment]
We should thank valgrind!

**Pull request merged**
