### PR TITLE
Documented new mr ops in fi_gni

### LINKED ISSUE #850: Document new MR domain_ops in the fi_gni man page
Document changes from #844, #848, #848

### PR DESCRIPTION
**Pull request by jswaro**
Added documentation for GNI_MR_CACHE, GNI_MR_HARD_REG_LIMIT,
GNI_SOFT_REG_LIMIT, GNI_MR_HARD_STALE_REG_LIMIT, GNI_MR_UDREG_LIMIT,
and GNI_MR_UDREG_LIMIT

closes #850

Signed-off-by: James Swaro jswaro@cray.com
@sungeunchoi @hppritcha

### CODE REVIEW

**Comment by sungeunchoi** [comment]
I don't like the word _implies_ in the description.  I'd prefer something like:

"... The value is of type int32_t (-1 for no limit)."

**Comment by hppritcha** [comment]
Looks good to me modulo the _implies_

**Comment by jswaro** [comment]
Ok

**Comment by sungeunchoi** [comment]
👍

**Pull request merged**
