### PR TITLE
Revert change to mem reg to adjust buffer boundary

### LINKED ISSUE #667: OpenMPI osu_get_acc_latency gets memory registration warnings
The osu_get_acc_latency benchmark gets a large number of warnings regarding memory registration for sizes > 131072.

```
% srun -n2 -N2 -t00:2:00 --exclusive ./osu_get_acc_latency
# OSU MPI_Get_accumulate latency Test v5.0
# Window creation: MPI_Win_allocate
# Synchronization: MPI_Win_flush
# Size          Latency (us)
...
libfabric:gni:mr:__mr_cache_create_registration():1345<warn> [19617:1] failed to register memory with uGNI, ret=GNI_RC_INVALID_PARAM
libfabric:gni:mr:__mr_cache_search_inuse():1180<warn> [19617:1] failure in registration, can't really recover at this point since we've already retired the existing entries
```

### PR DESCRIPTION
**Pull request by jswaro**
Signed-off-by: James Swaro jswaro@cray.com

closes #667

### CODE REVIEW

**Comment by jswaro** [comment]
@hppritcha @sungeunchoi @ztiffany 

Review when possible.

**Comment by sungeunchoi** [comment]
Do you know why this was an issue?

**Comment by jswaro** [comment]
The registered address was outside of the mapped memory region. This could occur because we were modifying the provided address to be page boundary aligned as an optimization.

**Comment by sungeunchoi** [comment]
Is there anyway to detect this and only page align when the new address is legal?  e.g., try again with original address is it fails?  Seems like disabling it entirely is a bit heavy handed.

**Comment by jswaro** [comment]
There is some caution here. If we register something they didn't plan to register and they write to it, they would succeed since we've registered it without them knowing. There is that danger. This should eliminate that danger as well.

**Comment by jswaro** [comment]
We can certainly retry if the original fails, but that requires knowing the original address and length. Neither of which is passed in.

**Comment by sungeunchoi** [comment]
Another option is to add a domain open_ops that enables this optimization (disabled by default), which would be documented in our man page as possibly registering memory that was not explicitly requested.

**Pull request closed without merging**
