### PR TITLE
Resize hashtable on element removal to decrease memory footprint

### LINKED ISSUE #137: Add resize on removal for the hashtable implementation to reduce memory usage
As the title implies, the hash table doesn't resize on removal. The dominating factor in memory growth is the per-element usage of memory. However, during long idle period on sparse tables, or on memory constrained environments, it would be ideal to reduce the memory utilization on removal.

### PR DESCRIPTION
**Pull request by jswaro**
If the removal of an element would decrease the element to bucket ratio
below the threshold for a downsized table, the hash table should resize
to reduce memory consumption. This commit assumes that the new table will
have an approximate element to bucket ratio which is a fraction of the
collision threshold

Signed-off-by: James Swaro jswaro@cray.com

```
modified:   prov/gni/src/gnix_hashtable.c
modified:   prov/gni/test/hashtable.c
```

closes #137

### CODE REVIEW

**Comment by jswaro** [comment]
@hppritcha, @bturrubiates, @ztiffany, @sungeunchoi 

Please review when you have an opportunity

**Comment by ztiffany** [comment]
:+1:

**Comment by bturrubiates** [comment]
Looks good to me.

**Comment by hppritcha** [comment]
same for me.  looks good.

**Pull request merged**
